name: Ubuntu image build
on:
  workflow_dispatch:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: noble
        type: string
  workflow_call:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: noble
        type: string

# variables path are inconsistent when triggering with workflow_dispatch
# or workflow_call.
jobs:
  build:

    strategy:
      matrix:
        arch:
          - name: 'amd64'
            os: ubuntu-24.04
            mirror: http://azure.archive.ubuntu.com/ubuntu
    runs-on: ${{ matrix.arch.os }}
    env:
      SERIES: ${{ github.event.inputs.series || inputs.series }}
      DRIVER_VERSION: '570'
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: update APT cache
        run: sudo apt-get update
      - name: installing dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
                qemu-utils \
                debootstrap
      - name: installing genesis
        run: sudo python3 -m pip install git+https://github.com/gjolly/genesis.git@main
      - name: running debootstrap
        run: sudo genesis debootstrap --output ./rootfs --series $SERIES --mirror "${{ matrix.arch.mirror }}"
      - name: creating tarball
        run: sudo tar czf rootfs.tar.gz ./rootfs

      - name: creating disk-image
        run: sudo genesis create-disk --size 4 --rootfs-dir ./rootfs
      - name: Updating the system
        run: |
          sudo genesis update-system \
            --disk-image disk.img \
            --mirror "${{ matrix.arch.mirror }}" \
            --series "$SERIES" \
            --extra-package vim \
            --extra-package ca-certificates \
            --extra-package openssh-server \
            --extra-package cloud-init \
            --extra-package curl \
            --extra-package "linux-modules-nvidia-${DRIVER_VERSION}-server-generic" \
            --extra-package "nvidia-utils-${DRIVER_VERSION}-server" \
            --extra-package linux-generic
      # see https://forums.developer.nvidia.com/t/nvrm-this-pci-i-o-region-assigned-to-your-nvidia-device-is-invalid/229899/2
      - name: Configure Kernel command line
        run: |
          echo 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX pci=realloc"' > zz-cmdline.cfg
          sudo genesis copy-files \
            --disk-image disk.img \
            --file ./zz-cmdline.cfg:/etc/default/grub.d/zz-cmdline.cfg
      - name: Install Grub
        run: |
          sudo genesis install-grub --disk-image disk.img
      - name: Converting to qcow2
        run: |
          sudo qemu-img convert -f raw -O qcow2 disk.img disk.qcow2
      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: disk.qcow2
