name: Ubuntu image build
on:
  workflow_dispatch:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: noble
        type: string
  workflow_call:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: noble
        type: string

# variables path are inconsistent when triggering with workflow_dispatch
# or workflow_call.
jobs:
  build:

    strategy:
      matrix:
        arch:
          - name: 'amd64'
            os: ubuntu-24.04
            mirror: http://azure.archive.ubuntu.com/ubuntu
          - name: 'arm64'
            os: ubuntu-24.04-arm
            mirror: http://azure.ports.ubuntu.com/ubuntu-ports
    environment: secrets
    runs-on: ${{ matrix.arch.os }}
    env:
      SERIES: ${{ github.event.inputs.series || inputs.series }}
      ORACLE_BUCKET_URL: https://objectstorage.eu-marseille-1.oraclecloud.com/p/${{ secrets.ORACLE_BUCKET_TOKEN }}/n/axd1qa3z3pet/b/live-images/o
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: update APT cache
        run: sudo apt-get update
      - name: installing dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
                qemu-utils \
                debootstrap
      - name: installing genesis
        run: sudo python3 -m pip install git+https://github.com/gjolly/genesis.git@main
      - name: running debootstrap
        run: sudo genesis debootstrap --output ./rootfs --series $SERIES --mirror "${{ matrix.arch.mirror }}"
      - name: creating tarball
        run: sudo tar czf rootfs.tar.gz ./rootfs

      - name: creating disk-image
        run: sudo genesis create-disk --rootfs-dir ./rootfs
      - name: Updating the system
        run: |
          sudo genesis update-system \
            --disk-image disk.img \
            --mirror "${{ matrix.arch.mirror }}" \
            --series "$SERIES" \
            --extra-package vim \
            --extra-package ca-certificates \
            --extra-package openssh-server \
            --extra-package cloud-init \
            --extra-package curl \
            --extra-package linux-modules-nvidia-570-generic \
            --extra-package linux-generic
      - name: Install Grub
        run: |
          sudo genesis install-grub --disk-image disk.img
      - name: Converting to qcow2
        run: |
          sudo qemu-img convert -f raw -O qcow2 disk.img disk.qcow2
      - name: Saving disk-image
        run: |
          curl -X PUT -T disk.qcow2 \
            -H "Content-Type: application/octet-stream" \
            "$ORACLE_BUCKET_URL/$SERIES-${{ matrix.arch.name }}.img"

      - name: Attest Artifacts
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'disk.img'

      - name: Saving attestation
        run: |
          curl -X PUT -T ${{ steps.attest.outputs.bundle-path }} \
            -H "Content-Type: application/json" \
            "$ORACLE_BUCKET_URL/$SERIES-${{ matrix.arch.name }}.attestation.json"
